### ISSUE TITLE
Gemini Exchange - Encoding Issue

### ISSUE THREAD

**Issue by LevinTheDream** [kroitor/ccxt#113]
Gemini Exchange
Python 3.6
Most recent ccxt
Same as issue  #30 

Testing private api functionality.

`gemini = ccxt.gemini()
gemini.apiKey = 'MY_KEY'
gemini.secret = 'MY_SECRET'
balance = gemini.fetch_balance()`

Throws this:

> Traceback (most recent call last):
  File ".../main.py", line 51, in <module>
    balance = gemini.fetch_balance()
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\ccxt\__init__.py", line 8908, in fetch_balance
    balances = self.privatePostBalances()
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\ccxt\__init__.py", line 8957, in request
    payload = base64.b64encode(payload)
  File "C:\Program Files (x86)\Python36-32\lib\base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'str'

**Comment by LevinTheDream** [comment]
Closing for similarity to #30
