### ISSUE TITLE
TypeError when fetching ticker in Python 3.6

### ISSUE THREAD

**Issue by gnmerritt** [kroitor/ccxt#140]
Version 1.4.79, getting a type error when trying to fetch ticker info. Just posting this here in case other people have ran into it, will try and figure out a fix tomorrow when I have some time... First half of the stack trace is my stuff, but it shows the calling method and the exchange/symbol so that might help. 

```
Exception fetching USDT-BTC from bittrex
  File "/home/nathan/sources/coinbot/strategies/apis.py", line 35, in fetch_json
    return lower_key(self.ccxt.fetch_ticker(symbol))
  File "/home/nathan/.virtualenvs/coins/lib/python3.6/site-packages/ccxt/exchanges.py", line 3108, in fetch_ticker
    'market': m['id'],
TypeError: string indices must be integers
```

**Comment by kroitor** [comment]
Thx, will check this now.

**Comment by kroitor** [comment]
Can you please show your code?

**Comment by kroitor** [comment]
```shell
mbp:ccxt igorkroitor$ python3
Python 3.6.1 (default, Jul 10 2017, 04:32:51) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> print(ccxt.bittrex().fetch_ticker('BTC/USDT'))
{'timestamp': 1503372792000, 'datetime': '2017-08-22T03:33:12.000Z', 'high': 4092.99999999, 'low': 3800.0, 'bid': 3834.00000004, 'ask': 3862.99999999, 'vwap': None, 'open': None, 'close': None, 'first': None, 'last': 3836.0, 'change': None, 'percentage': None, 'average': None, 'baseVolume': 19164469.01607284, 'quoteVolume': 4836.9618462, 'info': {'MarketName': 'USDT-BTC', 'High': 4092.99999999, 'Low': 3800.0, 'Volume': 4836.9618462, 'Last': 3836.0, 'BaseVolume': 19164469.01607284, 'TimeStamp': '2017-08-22T03:33:12.587', 'Bid': 3834.00000004, 'Ask': 3862.99999999, 'OpenBuyOrders': 2892, 'OpenSellOrders': 2389, 'PrevDay': 4073.2, 'Created': '2015-12-11T06:31:40.633'}}
>>> 
```

I'm not able to reproduce your error, need more info: relevant code + full output.

Does the following work for you:

```Python
import ccxt
print(ccxt.bittrex().fetch_ticker('BTC/USDT'))
```

?

**Comment by thijstriemstra** [comment]
Also ran into this issue a couple of times.

```python
>>> print(ccxt.bittrex().fetch_ticker('BTC'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/foo/bar/ccxt/ccxt/exchanges.py", line 3098, in fetch_ticker
    'market': m['id'],
TypeError: string indices must be integers
```

**Comment by kroitor** [comment]
> Also ran into this issue a couple of times.

fetch_ticker ('BTC') ? why not BTC/something or something/BTC? )

**Comment by kroitor** [comment]
I will add a human readable exception for errors related to the symbol-literal.
@thijstriemstra , does the following work for you?
```
import ccxt
print(ccxt.bittrex().fetch_ticker('BTC/USDT'))
```

**Comment by kroitor** [comment]
@gnmerritt the error you get is probably due to improperly used symbols. Bittrex does not have a `USDT-BTC` symbol, print(bittrex.symbols) to see all of them. Bittrex has `BTC/USDT` symbol for the market id `USDT-BTC`...

```
bittrex has 261 symbols: 1ST/BTC, 1ST/ETH, 2GIVE/BTC, ABY/BTC, ADT/BTC, ADT/ETH, ADX/BTC, 
ADX/ETH, AEON/BTC, AGRS/BTC, AMP/BTC, ANT/BTC, ANT/ETH, APX/BTC, ARDR/BTC, ARK/BTC, 
AUR/BTC, BAT/BTC, BAT/ETH, BAY/BTC, BCH/BTC, BCH/ETH, BCH/USDT, BCY/BTC, BITB/BTC, 
BLITZ/BTC, BLK/BTC, BLOCK/BTC, BNT/BTC, BNT/ETH, BRK/BTC, BRX/BTC, BSD/BTC, BTA/BTC, 
BTC/BITCNY, BTC/USDT, BTCD/BTC, BTS/BTC, BTS/ETH, BURST/BTC, BYC/BTC, CANN/BTC, 
CFI/BTC, CFI/ETH, CLAM/BTC, CLOAK/BTC, CLUB/BTC, COVAL/BTC, CPC/BTC, CRB/BTC, 
CRB/ETH, CRW/BTC, CURE/BTC, CVC/BTC, CVC/ETH, DAR/BTC, DASH/BTC, DASH/ETH, 
DASH/USDT, DCR/BTC, DCT/BTC, DGB/BTC, DGB/ETH, DGD/BTC, DGD/ETH, DMD/BTC, 
DOGE/BTC, DOPE/BTC, DRACO/BTC, DTB/BTC, DYN/BTC, EBST/BTC, EDG/BTC, EFL/BTC, 
EGC/BTC, EMC/BTC, EMC2/BTC, ENRG/BTC, ERC/BTC, ETC/BTC, ETC/ETH, ETC/USDT, ETH/BTC, 
ETH/USDT, EXCL/BTC, EXP/BTC, FAIR/BTC, FCT/BTC, FCT/ETH, FLDC/BTC, FLO/BTC, FTC/BTC, 
FUN/BTC, FUN/ETH, GAM/BTC, GAME/BTC, GBG/BTC, GBYTE/BTC, GCR/BTC, GEO/BTC, GLD/BTC, 
GNO/BTC, GNO/ETH, GNT/BTC, GNT/ETH, GOLOS/BTC, GRC/BTC, GRS/BTC, GUP/BTC, GUP/ETH, 
HKG/BTC, HMQ/BTC, HMQ/ETH, INCNT/BTC, INFX/BTC, IOC/BTC, ION/BTC, IOP/BTC, KMD/BTC, 
KORE/BTC, LBC/BTC, LGD/BTC, LGD/ETH, LMC/BTC, LSK/BTC, LTC/BTC, LTC/ETH, LTC/USDT, 
LUN/BTC, LUN/ETH, MAID/BTC, MCO/BTC, MCO/ETH, MEME/BTC, MLN/BTC, MONA/BTC, 
MTL/BTC, MTL/ETH, MUE/BTC, MUSIC/BTC, MYST/BTC, MYST/ETH, NAUT/BTC, NAV/BTC, 
NBT/BTC, NEO/BTC, NEO/ETH, NEO/USDT, NEOS/BTC, NLG/BTC, NMR/BTC, NMR/ETH, NXC/BTC, 
NXS/BTC, NXT/BTC, OK/BTC, OMG/BTC, OMG/ETH, OMNI/BTC, PART/BTC, PAY/BTC, PAY/ETH, 
PDC/BTC, PINK/BTC, PIVX/BTC, PKB/BTC, POT/BTC, PPC/BTC, PTC/BTC, PTOY/BTC, PTOY/ETH, 
QRL/BTC, QRL/ETH, QTUM/BTC, QTUM/ETH, QWARK/BTC, RADS/BTC, RBY/BTC, RDD/BTC, 
REP/BTC, REP/ETH, RISE/BTC, RLC/BTC, RLC/ETH, SAFEX/BTC, SBD/BTC, SC/BTC, SC/ETH, 
SEQ/BTC, SHIFT/BTC, SIB/BTC, SLR/BTC, SLS/BTC, SNGLS/BTC, SNGLS/ETH, SNRG/BTC, 
SNT/BTC, SNT/ETH, SPHR/BTC, SPR/BTC, START/BTC, STEEM/BTC, STORJ/BTC, STORJ/ETH, 
STRAT/BTC, STRAT/ETH, SWIFT/BTC, SWT/BTC, SYNX/BTC, SYS/BTC, THC/BTC, TIME/BTC, 
TIME/ETH, TKN/BTC, TKN/ETH, TKS/BTC, TRIG/BTC, TRST/BTC, TRST/ETH, TRUST/BTC, TX/BTC, 
UBQ/BTC, UNB/BTC, UNO/BTC, VIA/BTC, VOX/BTC, VRC/BTC, VRM/BTC, VTC/BTC, VTR/BTC, 
WAVES/BTC, WAVES/ETH, WINGS/BTC, WINGS/ETH, XAUR/BTC, XBB/BTC, XCP/BTC, XDN/BTC, 
XEL/BTC, XEM/BTC, XEM/ETH, XLM/BTC, XLM/ETH, XMG/BTC, XMR/BTC, XMR/ETH, XMR/USDT, 
XMY/BTC, XRP/BTC, XRP/ETH, XRP/USDT, XST/BTC, XVC/BTC, XVG/BTC, XWC/BTC, XZC/BTC, 
ZCL/BTC, ZEC/BTC, ZEC/ETH, ZEC/USDT, ZEN/BTC

id              symbol          base            quote          
BTC-1ST         1ST/BTC         1ST             BTC            
ETH-1ST         1ST/ETH         1ST             ETH            
BTC-2GIVE       2GIVE/BTC       2GIVE           BTC            
BTC-ABY         ABY/BTC         ABY             BTC            
BTC-ADT         ADT/BTC         ADT             BTC            
ETH-ADT         ADT/ETH         ADT             ETH            
BTC-ADX         ADX/BTC         ADX             BTC            
ETH-ADX         ADX/ETH         ADX             ETH            
BTC-AEON        AEON/BTC        AEON            BTC            
BTC-AGRS        AGRS/BTC        AGRS            BTC            
BTC-AMP         AMP/BTC         AMP             BTC            
BTC-ANT         ANT/BTC         ANT             BTC            
ETH-ANT         ANT/ETH         ANT             ETH            
BTC-APX         APX/BTC         APX             BTC            
BTC-ARDR        ARDR/BTC        ARDR            BTC            
BTC-ARK         ARK/BTC         ARK             BTC            
BTC-AUR         AUR/BTC         AUR             BTC            
BTC-BAT         BAT/BTC         BAT             BTC            
ETH-BAT         BAT/ETH         BAT             ETH            
BTC-BAY         BAY/BTC         BAY             BTC            
BTC-BCC         BCH/BTC         BCH             BTC            
ETH-BCC         BCH/ETH         BCH             ETH            
USDT-BCC        BCH/USDT        BCH             USDT           
BTC-BCY         BCY/BTC         BCY             BTC            
BTC-BITB        BITB/BTC        BITB            BTC            
BTC-BLITZ       BLITZ/BTC       BLITZ           BTC            
BTC-BLK         BLK/BTC         BLK             BTC            
BTC-BLOCK       BLOCK/BTC       BLOCK           BTC            
BTC-BNT         BNT/BTC         BNT             BTC            
ETH-BNT         BNT/ETH         BNT             ETH            
BTC-BRK         BRK/BTC         BRK             BTC            
BTC-BRX         BRX/BTC         BRX             BTC            
BTC-BSD         BSD/BTC         BSD             BTC            
BTC-BTA         BTA/BTC         BTA             BTC            
BITCNY-BTC      BTC/BITCNY      BTC             BITCNY         
USDT-BTC        BTC/USDT        BTC             USDT           
BTC-BTCD        BTCD/BTC        BTCD            BTC            
BTC-BTS         BTS/BTC         BTS             BTC            
ETH-BTS         BTS/ETH         BTS             ETH            
BTC-BURST       BURST/BTC       BURST           BTC            
BTC-BYC         BYC/BTC         BYC             BTC            
BTC-CANN        CANN/BTC        CANN            BTC            
BTC-CFI         CFI/BTC         CFI             BTC            
ETH-CFI         CFI/ETH         CFI             ETH            
BTC-CLAM        CLAM/BTC        CLAM            BTC            
BTC-CLOAK       CLOAK/BTC       CLOAK           BTC            
BTC-CLUB        CLUB/BTC        CLUB            BTC            
BTC-COVAL       COVAL/BTC       COVAL           BTC            
BTC-CPC         CPC/BTC         CPC             BTC            
BTC-CRB         CRB/BTC         CRB             BTC            
ETH-CRB         CRB/ETH         CRB             ETH            
BTC-CRW         CRW/BTC         CRW             BTC            
BTC-CURE        CURE/BTC        CURE            BTC            
BTC-CVC         CVC/BTC         CVC             BTC            
ETH-CVC         CVC/ETH         CVC             ETH            
BTC-DAR         DAR/BTC         DAR             BTC            
BTC-DASH        DASH/BTC        DASH            BTC            
ETH-DASH        DASH/ETH        DASH            ETH            
USDT-DASH       DASH/USDT       DASH            USDT           
BTC-DCR         DCR/BTC         DCR             BTC            
BTC-DCT         DCT/BTC         DCT             BTC            
BTC-DGB         DGB/BTC         DGB             BTC            
ETH-DGB         DGB/ETH         DGB             ETH            
BTC-DGD         DGD/BTC         DGD             BTC            
ETH-DGD         DGD/ETH         DGD             ETH            
BTC-DMD         DMD/BTC         DMD             BTC            
BTC-DOGE        DOGE/BTC        DOGE            BTC            
BTC-DOPE        DOPE/BTC        DOPE            BTC            
BTC-DRACO       DRACO/BTC       DRACO           BTC            
BTC-DTB         DTB/BTC         DTB             BTC            
BTC-DYN         DYN/BTC         DYN             BTC            
BTC-EBST        EBST/BTC        EBST            BTC            
BTC-EDG         EDG/BTC         EDG             BTC            
BTC-EFL         EFL/BTC         EFL             BTC            
BTC-EGC         EGC/BTC         EGC             BTC            
BTC-EMC         EMC/BTC         EMC             BTC            
BTC-EMC2        EMC2/BTC        EMC2            BTC            
BTC-ENRG        ENRG/BTC        ENRG            BTC            
BTC-ERC         ERC/BTC         ERC             BTC            
BTC-ETC         ETC/BTC         ETC             BTC            
ETH-ETC         ETC/ETH         ETC             ETH            
USDT-ETC        ETC/USDT        ETC             USDT           
BTC-ETH         ETH/BTC         ETH             BTC            
USDT-ETH        ETH/USDT        ETH             USDT           
BTC-EXCL        EXCL/BTC        EXCL            BTC            
BTC-EXP         EXP/BTC         EXP             BTC            
BTC-FAIR        FAIR/BTC        FAIR            BTC            
BTC-FCT         FCT/BTC         FCT             BTC            
ETH-FCT         FCT/ETH         FCT             ETH            
BTC-FLDC        FLDC/BTC        FLDC            BTC            
BTC-FLO         FLO/BTC         FLO             BTC            
BTC-FTC         FTC/BTC         FTC             BTC            
BTC-FUN         FUN/BTC         FUN             BTC            
ETH-FUN         FUN/ETH         FUN             ETH            
BTC-GAM         GAM/BTC         GAM             BTC            
BTC-GAME        GAME/BTC        GAME            BTC            
BTC-GBG         GBG/BTC         GBG             BTC            
BTC-GBYTE       GBYTE/BTC       GBYTE           BTC            
BTC-GCR         GCR/BTC         GCR             BTC            
BTC-GEO         GEO/BTC         GEO             BTC            
BTC-GLD         GLD/BTC         GLD             BTC            
BTC-GNO         GNO/BTC         GNO             BTC            
ETH-GNO         GNO/ETH         GNO             ETH            
BTC-GNT         GNT/BTC         GNT             BTC            
ETH-GNT         GNT/ETH         GNT             ETH            
BTC-GOLOS       GOLOS/BTC       GOLOS           BTC            
BTC-GRC         GRC/BTC         GRC             BTC            
BTC-GRS         GRS/BTC         GRS             BTC            
BTC-GUP         GUP/BTC         GUP             BTC            
ETH-GUP         GUP/ETH         GUP             ETH            
BTC-HKG         HKG/BTC         HKG             BTC            
BTC-HMQ         HMQ/BTC         HMQ             BTC            
ETH-HMQ         HMQ/ETH         HMQ             ETH            
BTC-INCNT       INCNT/BTC       INCNT           BTC            
BTC-INFX        INFX/BTC        INFX            BTC            
BTC-IOC         IOC/BTC         IOC             BTC            
BTC-ION         ION/BTC         ION             BTC            
BTC-IOP         IOP/BTC         IOP             BTC            
BTC-KMD         KMD/BTC         KMD             BTC            
BTC-KORE        KORE/BTC        KORE            BTC            
BTC-LBC         LBC/BTC         LBC             BTC            
BTC-LGD         LGD/BTC         LGD             BTC            
ETH-LGD         LGD/ETH         LGD             ETH            
BTC-LMC         LMC/BTC         LMC             BTC            
BTC-LSK         LSK/BTC         LSK             BTC            
BTC-LTC         LTC/BTC         LTC             BTC            
ETH-LTC         LTC/ETH         LTC             ETH            
USDT-LTC        LTC/USDT        LTC             USDT           
BTC-LUN         LUN/BTC         LUN             BTC            
ETH-LUN         LUN/ETH         LUN             ETH            
BTC-MAID        MAID/BTC        MAID            BTC            
BTC-MCO         MCO/BTC         MCO             BTC            
ETH-MCO         MCO/ETH         MCO             ETH            
BTC-MEME        MEME/BTC        MEME            BTC            
BTC-MLN         MLN/BTC         MLN             BTC            
BTC-MONA        MONA/BTC        MONA            BTC            
BTC-MTL         MTL/BTC         MTL             BTC            
ETH-MTL         MTL/ETH         MTL             ETH            
BTC-MUE         MUE/BTC         MUE             BTC            
BTC-MUSIC       MUSIC/BTC       MUSIC           BTC            
BTC-MYST        MYST/BTC        MYST            BTC            
ETH-MYST        MYST/ETH        MYST            ETH            
BTC-NAUT        NAUT/BTC        NAUT            BTC            
BTC-NAV         NAV/BTC         NAV             BTC            
BTC-NBT         NBT/BTC         NBT             BTC            
BTC-NEO         NEO/BTC         NEO             BTC            
ETH-NEO         NEO/ETH         NEO             ETH            
USDT-NEO        NEO/USDT        NEO             USDT           
BTC-NEOS        NEOS/BTC        NEOS            BTC            
BTC-NLG         NLG/BTC         NLG             BTC            
BTC-NMR         NMR/BTC         NMR             BTC            
ETH-NMR         NMR/ETH         NMR             ETH            
BTC-NXC         NXC/BTC         NXC             BTC            
BTC-NXS         NXS/BTC         NXS             BTC            
BTC-NXT         NXT/BTC         NXT             BTC            
BTC-OK          OK/BTC          OK              BTC            
BTC-OMG         OMG/BTC         OMG             BTC            
ETH-OMG         OMG/ETH         OMG             ETH            
BTC-OMNI        OMNI/BTC        OMNI            BTC            
BTC-PART        PART/BTC        PART            BTC            
BTC-PAY         PAY/BTC         PAY             BTC            
ETH-PAY         PAY/ETH         PAY             ETH            
BTC-PDC         PDC/BTC         PDC             BTC            
BTC-PINK        PINK/BTC        PINK            BTC            
BTC-PIVX        PIVX/BTC        PIVX            BTC            
BTC-PKB         PKB/BTC         PKB             BTC            
BTC-POT         POT/BTC         POT             BTC            
BTC-PPC         PPC/BTC         PPC             BTC            
BTC-PTC         PTC/BTC         PTC             BTC            
BTC-PTOY        PTOY/BTC        PTOY            BTC            
ETH-PTOY        PTOY/ETH        PTOY            ETH            
BTC-QRL         QRL/BTC         QRL             BTC            
ETH-QRL         QRL/ETH         QRL             ETH            
BTC-QTUM        QTUM/BTC        QTUM            BTC            
ETH-QTUM        QTUM/ETH        QTUM            ETH            
BTC-QWARK       QWARK/BTC       QWARK           BTC            
BTC-RADS        RADS/BTC        RADS            BTC            
BTC-RBY         RBY/BTC         RBY             BTC            
BTC-RDD         RDD/BTC         RDD             BTC            
BTC-REP         REP/BTC         REP             BTC            
ETH-REP         REP/ETH         REP             ETH            
BTC-RISE        RISE/BTC        RISE            BTC            
BTC-RLC         RLC/BTC         RLC             BTC            
ETH-RLC         RLC/ETH         RLC             ETH            
BTC-SAFEX       SAFEX/BTC       SAFEX           BTC            
BTC-SBD         SBD/BTC         SBD             BTC            
BTC-SC          SC/BTC          SC              BTC            
ETH-SC          SC/ETH          SC              ETH            
BTC-SEQ         SEQ/BTC         SEQ             BTC            
BTC-SHIFT       SHIFT/BTC       SHIFT           BTC            
BTC-SIB         SIB/BTC         SIB             BTC            
BTC-SLR         SLR/BTC         SLR             BTC            
BTC-SLS         SLS/BTC         SLS             BTC            
BTC-SNGLS       SNGLS/BTC       SNGLS           BTC            
ETH-SNGLS       SNGLS/ETH       SNGLS           ETH            
BTC-SNRG        SNRG/BTC        SNRG            BTC            
BTC-SNT         SNT/BTC         SNT             BTC            
ETH-SNT         SNT/ETH         SNT             ETH            
BTC-SPHR        SPHR/BTC        SPHR            BTC            
BTC-SPR         SPR/BTC         SPR             BTC            
BTC-START       START/BTC       START           BTC            
BTC-STEEM       STEEM/BTC       STEEM           BTC            
BTC-STORJ       STORJ/BTC       STORJ           BTC            
ETH-STORJ       STORJ/ETH       STORJ           ETH            
BTC-STRAT       STRAT/BTC       STRAT           BTC            
ETH-STRAT       STRAT/ETH       STRAT           ETH            
BTC-SWIFT       SWIFT/BTC       SWIFT           BTC            
BTC-SWT         SWT/BTC         SWT             BTC            
BTC-SYNX        SYNX/BTC        SYNX            BTC            
BTC-SYS         SYS/BTC         SYS             BTC            
BTC-THC         THC/BTC         THC             BTC            
BTC-TIME        TIME/BTC        TIME            BTC            
ETH-TIME        TIME/ETH        TIME            ETH            
BTC-TKN         TKN/BTC         TKN             BTC            
ETH-TKN         TKN/ETH         TKN             ETH            
BTC-TKS         TKS/BTC         TKS             BTC            
BTC-TRIG        TRIG/BTC        TRIG            BTC            
BTC-TRST        TRST/BTC        TRST            BTC            
ETH-TRST        TRST/ETH        TRST            ETH            
BTC-TRUST       TRUST/BTC       TRUST           BTC            
BTC-TX          TX/BTC          TX              BTC            
BTC-UBQ         UBQ/BTC         UBQ             BTC            
BTC-UNB         UNB/BTC         UNB             BTC            
BTC-UNO         UNO/BTC         UNO             BTC            
BTC-VIA         VIA/BTC         VIA             BTC            
BTC-VOX         VOX/BTC         VOX             BTC            
BTC-VRC         VRC/BTC         VRC             BTC            
BTC-VRM         VRM/BTC         VRM             BTC            
BTC-VTC         VTC/BTC         VTC             BTC            
BTC-VTR         VTR/BTC         VTR             BTC            
BTC-WAVES       WAVES/BTC       WAVES           BTC            
ETH-WAVES       WAVES/ETH       WAVES           ETH            
BTC-WINGS       WINGS/BTC       WINGS           BTC            
ETH-WINGS       WINGS/ETH       WINGS           ETH            
BTC-XAUR        XAUR/BTC        XAUR            BTC            
BTC-XBB         XBB/BTC         XBB             BTC            
BTC-XCP         XCP/BTC         XCP             BTC            
BTC-XDN         XDN/BTC         XDN             BTC            
BTC-XEL         XEL/BTC         XEL             BTC            
BTC-XEM         XEM/BTC         XEM             BTC            
ETH-XEM         XEM/ETH         XEM             ETH            
BTC-XLM         XLM/BTC         XLM             BTC            
ETH-XLM         XLM/ETH         XLM             ETH            
BTC-XMG         XMG/BTC         XMG             BTC            
BTC-XMR         XMR/BTC         XMR             BTC            
ETH-XMR         XMR/ETH         XMR             ETH            
USDT-XMR        XMR/USDT        XMR             USDT           
BTC-XMY         XMY/BTC         XMY             BTC            
BTC-XRP         XRP/BTC         XRP             BTC            
ETH-XRP         XRP/ETH         XRP             ETH            
USDT-XRP        XRP/USDT        XRP             USDT           
BTC-XST         XST/BTC         XST             BTC            
BTC-XVC         XVC/BTC         XVC             BTC            
BTC-XVG         XVG/BTC         XVG             BTC            
BTC-XWC         XWC/BTC         XWC             BTC            
BTC-XZC         XZC/BTC         XZC             BTC            
BTC-ZCL         ZCL/BTC         ZCL             BTC            
BTC-ZEC         ZEC/BTC         ZEC             BTC            
ETH-ZEC         ZEC/ETH         ZEC             ETH            
USDT-ZEC        ZEC/USDT        ZEC             USDT           
BTC-ZEN         ZEN/BTC         ZEN             BTC     
```

**Comment by gnmerritt** [comment]
Ok, that makes sense. I just upgraded from a much older version so I guess the symbol stuff must have changed at some point? Thanks for investigating!

**Comment by kroitor** [comment]
> I just upgraded from a much older version so I guess the symbol stuff must have changed at some point?

Actually, not, it was designed that way from the very beginning, for such a library there's not much point in having all currencies inconsistently named across exchanges. The goal is to have them unified. Ids = non-unified (exchange-specific), symbols = unified.

**Comment by kroitor** [comment]
Thx for reporting anyway! Appreciate all feedback!

**Comment by thijstriemstra** [comment]
> why not BTC/XXX or YYY/BTC? It should be a pair of currencies with a slash (a symbol) ))

I know but that's how to reproduce the traceback ;)

**Comment by gnmerritt** [comment]
I was on a super old version (`ccxt==0.1.63`) which for some reason was accepting `USDT-BTC` but this symbol/id stuff you explained is way better anyway - I was doing the mapping between exchanges myself so I'm glad to upgrade and have you guys do it. Thanks for taking a look!

**Comment by kroitor** [comment]
@gnmerritt no problem, let us know if you have any other questions)
