### ISSUE TITLE
Hitbtc Load Markets problem.

### ISSUE THREAD

**Issue by burakkaptan** [kroitor/ccxt#159]
Hi, 

When I write this: 
`hitbtc = ccxt.hitbtc()
hitbtc.load_markets()
`

I get the following error: 
_Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\exchange.py", line 210, in fetch
    response = opener.open(request, timeout=int(self.timeout / 1000))
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Desktop\python-ccxt\exercise1.py", line 10, in <module>
    print( hitbtc.load_markets() )
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\exchange.py", line 562, in load_markets
    markets = self.fetch_markets()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\exchanges.py", line 9398, in fetch_markets
    markets = self.publicGetSymbols()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\exchanges.py", line 9563, in request
    response = self.fetch(url, method, headers, body)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\exchange.py", line 249, in fetch
    self.raise_error(ExchangeNotAvailable, url, method, e)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\exchange.py", line 182, in raise_error
    details,
ccxt.errors.ExchangeNotAvailable: hitbtc GET http://api.hitbtc.com/api/1/public/symbols <urlopen error [Errno 11001] getaddrinfo failed>
[Finished in 2.6s]_

**Comment by kroitor** [comment]
Hello, @burakkaptan !
Can you try running the symbols example from your console?

https://github.com/kroitor/ccxt/blob/master/examples/py/symbols.py

```shell
# type this in your shell in ccxt directory
python3 examples/py/symbols.py hitbtc
```

Also, what's your country? Turkey?
Can you ping HitBTC and reach it with your browser?
Because to me it seems like a DNS problem on your side.

To help you we need a snippet of code from you to run and test against. Can you paste a minimal code sample reproducing the problem? Because it may be your local issue. In that case, it's covered in the [Troubleshooting](https://github.com/kroitor/ccxt/wiki#troubleshooting) section of the Manual.

I've just tested hitbtc.load_markets() and it works normally on my side.

<img width="699" alt="screen shot 2017-08-28 at 17 19 40" src="https://user-images.githubusercontent.com/1294454/29777593-45387f64-8c15-11e7-906c-645956eded08.png">

**Comment by burakkaptan** [comment]
I just ran the symbols.py through my console. It shows me a list of the supported exchanges. 
Yes, I live in Turkey, I can reach Hitbtc via my browser

I enclosed the screenshot of my codes: 
![adsiz](https://user-images.githubusercontent.com/6393475/29810132-5b980c38-8ca7-11e7-926f-366f56aca811.png)

**Comment by kroitor** [comment]
> I just ran the symbols.py through my console. It shows me a list of the supported exchanges.

You should run it precisely as I wrote it, if you want to test against HitBTC:

```shell
python3 examples/py/symbols.py hitbtc
```

If it does not work for you, try pinging api.hitbtc.com from console, it may be a networking issue. Also, do other exchanges work, is this issue common to all of them as seen on your side, or is it only relevant to hitbtc?
