### ISSUE TITLE
Python fetch_trades not working on GDAX

### ISSUE THREAD

**Issue by MartianTech** [kroitor/ccxt#2]
Using
```
market = ccxt.gdax()
market.load_products()

for symbol in market.products:
    print (market.fetch_trades(symbol))
```
Throws error 

```
Traceback (most recent call last):
('gdax', 'GET', 'https://api.gdax.com/products/{id}/trades?symbol=LTC-USD', 404, 'Not Found', {u'message': u'NotFound'})
  File "/Users/admin/workspace/test-ccxt/test-ccxt.py", line 35, in <module>
    main()
  File "/Users/admin/workspace/test-ccxt/test-ccxt.py", line 27, in main
    print (market.fetch_trades(symbol))
  File "/usr/local/lib/python2.7/site-packages/ccxt/__init__.py", line 4000, in fetch_trades
    'symbol': self.product_id (product),
  File "/usr/local/lib/python2.7/site-packages/ccxt/__init__.py", line 4035, in request
    return self.fetch (url, method, headers, body)
  File "/usr/local/lib/python2.7/site-packages/ccxt/__init__.py", line 99, in fetch
    response = opener.open (request, timeout = self.timeout).read ().decode('utf-8')
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
```

It's working on other exchanges I tried.

**Comment by kroitor** [comment]
Thank you for your report!
I fixed it, check it out now )

**Comment by MartianTech** [comment]
Yea that was fast. Thanks!

**Comment by koushik72** [comment]
The same issue is happening for Php. Can you please fix that too?
Thank you.

**Comment by kroitor** [comment]
@koushik72 which version of CCXT do you have?

> The same issue is happening for Php. Can you please fix that too?

We don't have to, because PHP code is generated automatically, as explained here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support
