### ISSUE TITLE
Implementing coinmarketcap API for basic currency information

### ISSUE THREAD

**Issue by nmiculinic** [kroitor/ccxt#22]
I suggest using your unified names ("BTC", "ETH" and similar) and taking those to https://coinmarketcap.com/api/ with providing support to receive their data about price in EUR/USD and other useful information provided in response dictionary.

**Comment by kroitor** [comment]
WIll add coinmarketcap support, thanks!

**Comment by kroitor** [comment]
I added CoinMarketCap, look for the id in the code to see details.
Basically, it has only three possible methods:
```Python
coinmarketcap.loadProducts ()
coinmarketcap.fetchGlobal ([currency])  # default is 'USD', returns global data dictionary
coinmarketcap.fetchTickers ([currency]) # also 'USD', returns tickers indexed by symbols
coinmarketcap.fetchTicker (symbol)      # standard unified fetchTicker
```
Thanks!

**Comment by nmiculinic** [comment]
```python
cmc = ccxt.coinmarketcap()
cmc.load_products()
cmc.fetch_tickers()
```
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-18-d099b6980226> in <module>()
----> 1 cmc.fetch_tickers()

/usr/lib/python3.6/site-packages/ccxt/__init__.py in fetch_tickers(self, currency)
   4957             product = self.products_by_id[id]
   4958             symbol = product['symbol']
-> 4959             tickers[symbol] = self.parseTicker (ticker, product)
   4960         return tickers
   4961 

/usr/lib/python3.6/site-packages/ccxt/__init__.py in parseTicker(self, ticker, product)
   4938             'first': None,
   4939             'last': float (ticker[price]),
-> 4940             'change': float (ticker['percent_change_24h']),
   4941             'percentage': None,
   4942             'average': None,

TypeError: float() argument must be a string or a number, not 'NoneType'
```

Can you show me some example usage in python? Overall I'm having issues powering it up.

**Comment by kroitor** [comment]
This should work now, didn't meet those None values before. Sorry for the inconvenience. Everything now works as written above.
```
import ccxt
cmc = ccxt.coinmarketcap ()
cmc.load_products ()
cmc.fetch_tickers ()
```

**Comment by avatar-lavventura** [comment]
@kroitor : I have having following error:

```
import ccxt
cmc = ccxt.coinmarketcap ()
```

----------

```
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    cmc = ccxt.coinmarketcap ()
  File "/usr/local/lib/python2.7/site-packages/ccxt/base/exchange.py", line 303, in __init__
    self.web3 = Web3(HTTPProvider())
TypeError: __init__() takes at least 2 arguments (1 given)
```

**Comment by kroitor** [comment]
@avatar-lavventura what's your version of CCXT? Does that happen with the most recent version of it?

```
import ccxt
print(ccxt.__version__)
cmc = ccxt.coinmarketcap ()
```

?
