### ISSUE TITLE
Gatecoin Instantiation Error

### ISSUE THREAD

**Issue by cklester** [kroitor/ccxt#80]
Getting this error when instantiating Gatecoin:

```
{ Error: gatecoin GET https://api.gatecoin.com/Balance/Balances  Request with GET/HEAD method cannot have body
    at MarketNotAvailableError.CCXTError (ccxt.es5.js:39:116)
    at MarketNotAvailableError.MarketError (ccxt.es5.js:109:121)
    at new MarketNotAvailableError (ccxt.es5.js:126:145)
    at ccxt.es5.js:493:27
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7) constructor: [Function: MarketNotAvailableError] }
```

**Comment by kroitor** [comment]
Hi! Thanks for posting this! Will investigate and report soon.

**Comment by kroitor** [comment]
Ok, fixed it in version 1.1.151. Please update and try again.

**Comment by cklester** [comment]
Confirmed fixed. Thanks!

**Comment by kroitor** [comment]
Thanks!
